# Generated by Django 4.0.2 on 2022-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('veiculo', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('vendido', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
