# Generated by Django 4.0.2 on 2022-02-14 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veiculo', models.CharField(blank=True, max_length=120, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('vendido', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
